### ISSUE TITLE
[FEATURE] 채팅방 내 거래 예약하기

### ISSUE THREAD

**Issue by KIM-DO-HEE** [KIM-DO-HEE/hereyougo#31]
## 📄Description
채팅방 내에서 예약하기 버튼을 생성하여 예약을 하는 로직 작성하기

## ✅ Todo
- [ ] 채팅방에 예약하기 버튼 생성
- [ ] 예약하기 버튼을 클릭한 경우, 예약하는 팝업창을 띄우기
- [ ] 팝업창에서 예약하기 버튼 클릭 시 DB에 저장 및 거래 상태 변경하기
