### ISSUE TITLE
글 예약할 수 있는 api 작성

### ISSUE THREAD

**Issue by KIM-DO-HEE** [KIM-DO-HEE/hereyougo#40]
## 📄Description
-약속 잡기 버튼 클릭 후, 날짜/시간 수량 선택하면 예약을 할 수 있다
- Post 수량, 예약 수량에 따라 예약 가능 여부를 결정한다

## ✅ Todo
- [ ]  Appointment, Post : 예약 수량 추가, 예약 상태 추가
- [ ] 글 상태 추가 : 기부중, 기부완료
- [ ] Progress 단계 수정 => 예약중, 예약취소, 전달(거래) 완료
