### ISSUE TITLE
마이페이지 수정할 부분

### ISSUE THREAD

**Issue by KIM-DO-HEE** [KIM-DO-HEE/hereyougo#48]
## 📄Description
-회원은 자신이 예약한 글을 취소할 수 있다

## ✅ Todo
- [ ] 최소 너비 지정하기

약속목록 
- [ ] 예약 취소, 예약 완료 버튼이 없을 경우, 컬럼이 사라지는 문제 - thymeleaf

내가 쓴 글 목록 
- [ ] 목록 너비  문제 수정- css
- [ ] 전체 글 보기 버튼 너비 수정 - css
