### ISSUE TITLE
관심 카테고리 페이지 수정할 부분

### ISSUE THREAD

**Issue by KIM-DO-HEE** [KIM-DO-HEE/hereyougo#49]
## 📄Description
- 관심 카테고리 페이지 수정할 부분

## ✅ Todo
- [ ] 헤더 깨짐
- [ ] 중분류 안 불러오는 문제
- [ ] 관심 카테고리 등록 시 404로 이동
- [ ] 최소 높이 지정해주기 - css
