### ISSUE TITLE
마이페이지 추가 수정사항

### ISSUE THREAD

**Issue by KIM-DO-HEE** [KIM-DO-HEE/hereyougo#52]
## 📄Description
- 마이페이지 추가로 수정할 부분

## ✅ Todo
- [x] 관심 키워드 -> 관심 카테고리로 변경
- [ ] 약속 목록 -> '예약' 으로  용어 변경
- [ ] 내가 쓴 글 목록 -> '나의 최신 글'로 바꾸기

## 🔖ETC
